// transducers-js 0.4.180
// http://github.com/cognitect-labs/transducers-js
// 
// Copyright 2014-2015 Cognitect. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License..
;(function(){var d=this;
function f(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function g(a,b){var c=a.split("."),e=d;c[0]in e||!e.execScript||e.execScript("var "+c[0]);for(var k;c.length&&(k=c.shift());)c.length||void 0===b?e[k]?e=e[k]:e=e[k]={}:e[k]=b};var h="undefined"!=typeof Symbol?Symbol.iterator:"@@iterator",l="undefined"!=typeof Array.isArray?function(a){return Array.isArray(a)}:function(a){return"array"==f(a)};function m(a){return function(b){return!a.apply(null,Array.prototype.slice.call(arguments,0))}}function n(a){this.a=a}n.prototype["@@transducer/init"]=function(){throw Error("init not implemented");};n.prototype["@@transducer/result"]=function(a){return a};n.prototype["@@transducer/step"]=function(a,b){return this.a(a,b)};
function p(a){return"function"==typeof a?new n(a):a}function q(a){this["@@transducer/reduced"]=!0;this["@@transducer/value"]=a}function r(a){return new q(a)}function t(a){return a instanceof q||a&&a["@@transducer/reduced"]}function u(a){return t(a)?a:r(a)}function v(a){return a["@@transducer/value"]}function w(a){return t(a)?v(a):a}function x(a){return a}
function y(a){var b=arguments.length;if(2==b){var c=arguments[0],e=arguments[1];return function(a){return c(e.apply(null,Array.prototype.slice.call(arguments,0)))}}if(2<b)return z(y,arguments[0],Array.prototype.slice.call(arguments,1))}function A(a,b){this.b=a;this.a=b}A.prototype["@@transducer/init"]=function(){return this.a["@@transducer/init"]()};A.prototype["@@transducer/result"]=function(a){return this.a["@@transducer/result"](a)};
A.prototype["@@transducer/step"]=function(a,b){return this.a["@@transducer/step"](a,this.b(b))};function B(a){return function(b){return new A(a,b)}}function C(a,b){this.b=a;this.a=b}C.prototype["@@transducer/init"]=function(){return this.a["@@transducer/init"]()};C.prototype["@@transducer/result"]=function(a){return this.a["@@transducer/result"](a)};C.prototype["@@transducer/step"]=function(a,b){return this.b(b)?this.a["@@transducer/step"](a,b):a};
function D(a){return function(b){return new C(a,b)}}function E(a,b){this.b=a;this.a=b}E.prototype["@@transducer/init"]=function(){return this.a["@@transducer/init"]()};E.prototype["@@transducer/result"]=function(a){return this.a["@@transducer/result"](a)};E.prototype["@@transducer/step"]=function(a,b){0<this.b?a=this.a["@@transducer/step"](a,b):a=u(a);this.b--;return a};function F(a,b){this.b=a;this.a=b}F.prototype["@@transducer/init"]=function(){return this.a["@@transducer/init"]()};
F.prototype["@@transducer/result"]=function(a){return this.a["@@transducer/result"](a)};F.prototype["@@transducer/step"]=function(a,b){return this.b(b)?this.a["@@transducer/step"](a,b):r(a)};function G(a,b){this.b=-1;this.c=a;this.a=b}G.prototype["@@transducer/init"]=function(){return this.a["@@transducer/init"]()};G.prototype["@@transducer/result"]=function(a){return this.a["@@transducer/result"](a)};
G.prototype["@@transducer/step"]=function(a,b){this.b++;return 0==this.b%this.c?this.a["@@transducer/step"](a,b):a};function H(a,b){this.b=a;this.a=b}H.prototype["@@transducer/init"]=function(){return this.a["@@transducer/init"]()};H.prototype["@@transducer/result"]=function(a){return this.a["@@transducer/result"](a)};H.prototype["@@transducer/step"]=function(a,b){return 0<this.b?(this.b--,a):this.a["@@transducer/step"](a,b)};function I(a,b){this.b=!0;this.c=a;this.a=b}
I.prototype["@@transducer/init"]=function(){return this.a["@@transducer/init"]()};I.prototype["@@transducer/result"]=function(a){return this.a["@@transducer/result"](a)};I.prototype["@@transducer/step"]=function(a,b){if(this.b&&this.c(b))return a;this.b&&(this.b=!1);return this.a["@@transducer/step"](a,b)};var J={};function K(a,b){this.d=a;this.b=b;this.a=[];this.c=J}K.prototype["@@transducer/init"]=function(){return this.b["@@transducer/init"]()};
K.prototype["@@transducer/result"]=function(a){0<this.a.length&&(a=w(this.b["@@transducer/step"](a,this.a)),this.a=[]);return this.b["@@transducer/result"](a)};K.prototype["@@transducer/step"]=function(a,b){var c=this.c,e=this.d(b);this.c=e;if(c==J||c==e)return this.a.push(b),a;c=this.b["@@transducer/step"](a,this.a);this.a=[];t(c)||this.a.push(b);return c};function L(a,b){this.c=a;this.b=b;this.a=[]}L.prototype["@@transducer/init"]=function(){return this.b["@@transducer/init"]()};
L.prototype["@@transducer/result"]=function(a){0<this.a.length&&(a=w(this.b["@@transducer/step"](a,this.a)),this.a=[]);return this.b["@@transducer/result"](a)};L.prototype["@@transducer/step"]=function(a,b){this.a.push(b);if(this.c==this.a.length){var c=this.a;this.a=[];return this.b["@@transducer/step"](a,c)}return a};function M(a,b){this.b=a;this.a=b}M.prototype["@@transducer/init"]=function(){return this.a["@@transducer/init"]()};M.prototype["@@transducer/result"]=function(a){return this.a["@@transducer/result"](a)};
M.prototype["@@transducer/step"]=function(a,b){return null==this.b(b)?a:this.a["@@transducer/step"](a,b)};function N(a,b){this.b=-1;this.c=a;this.a=b}N.prototype["@@transducer/init"]=function(){return this.a["@@transducer/init"]()};N.prototype["@@transducer/result"]=function(a){return this.a["@@transducer/result"](a)};N.prototype["@@transducer/step"]=function(a,b){this.b++;return null==this.c(this.b,b)?a:this.a["@@transducer/step"](a,b)};
function O(a){return{"@@transducer/init":function(){return a["@@transducer/init"]()},"@@transducer/result":function(a){return a},"@@transducer/step":function(b,c){var e=a["@@transducer/step"](b,c);return t(e)?r(e):e}}}function P(a){var b=O(a);return{"@@transducer/init":function(){return a["@@transducer/init"]()},"@@transducer/result":function(b){return a["@@transducer/result"](b)},"@@transducer/step":function(a,e){return z(b,a,e)}}}
function z(a,b,c){if(c){a="function"==typeof a?p(a):a;if("string"==typeof c){var e=a;for(a=0;a<c.length;a++)if(b=e["@@transducer/step"](b,c.charAt(a)),t(b)){b=v(b);break}return e["@@transducer/result"](b)}if(l(c)){e=a;for(a=0;a<c.length;a++)if(b=e["@@transducer/step"](b,c[a]),t(b)){b=v(b);break}return e["@@transducer/result"](b)}if(c[h]||c.next){e=a;c[h]&&(c=c[h]());for(a=c.next();!a.done;){b=e["@@transducer/step"](b,a.value);if(t(b)){b=v(b);break}a=c.next()}return e["@@transducer/result"](b)}if("object"==
f(c)){for(e in c)if(c.hasOwnProperty(e)&&(b=a["@@transducer/step"](b,[e,c[e]]),t(b))){b=v(b);break}return a["@@transducer/result"](b)}throw Error("Cannot reduce instance of "+c.constructor.name);}}function Q(a,b,c,e){if(3==arguments.length){e=c;if("function"==typeof b)throw Error("If given only three arguments f must satisfy the ITransformer interface.");c=b["@@transducer/init"]()}b="function"==typeof b?p(b):b;a=a(b);return z(a,c,e)}function R(a,b){return a+b}function S(a,b){a.push(b);return a}
function T(a,b){a[b[0]]=b[1];return a}function U(a,b){this.b=a;this.a=b}U.prototype["@@transducer/init"]=function(){return this.a["@@transducer/init"]()};U.prototype["@@transducer/result"]=function(a){return this.b(a)};U.prototype["@@transducer/step"]=function(a,b){return this.a["@@transducer/step"](a,b)};var V=p(function(a,b){return r(b)});g("transducers.reduced",r);g("transducers.isReduced",t);g("transducers.comp",y);g("transducers.complement",m);g("transducers.identity",x);
g("transducers.transduce",Q);g("transducers.reduce",z);g("transducers.map",B);g("transducers.Map",A);g("transducers.filter",D);g("transducers.Filter",C);g("transducers.remove",function(a){return D(m(a))});g("transducers.Remove",{}.e);g("transducers.keep",function(a){return function(b){return new M(a,b)}});g("transducers.Keep",M);g("transducers.keepIndexed",function(a){return function(b){return new N(a,b)}});g("transducers.KeepIndexed",N);
g("transducers.take",function(a){return function(b){return new E(a,b)}});g("transducers.Take",E);g("transducers.takeWhile",function(a){return function(b){return new F(a,b)}});g("transducers.TakeWhile",F);g("transducers.takeNth",function(a){return function(b){return new G(a,b)}});g("transducers.TakeNth",G);g("transducers.drop",function(a){return function(b){return new H(a,b)}});g("transducers.Drop",H);g("transducers.dropWhile",function(a){return function(b){return new I(a,b)}});
g("transducers.DropWhile",I);g("transducers.partitionBy",function(a){return function(b){return new K(a,b)}});g("transducers.PartitionBy",K);g("transducers.partitionAll",function(a){return function(b){return new L(a,b)}});g("transducers.PartitionAll",L);g("transducers.completing",function(a,b){a="function"==typeof a?p(a):a;b=b||x;return new U(b,a)});g("transducers.Completing",U);g("transducers.wrap",p);g("transducers.Wrap",n);g("transducers.cat",P);
g("transducers.mapcat",function(a){return y(B(a),P)});g("transducers.into",function(a,b,c){if("string"==typeof a)return Q(b,R,a,c);if(l(a))return Q(b,S,a,c);if("object"==f(a))return Q(b,T,a,c)});g("transducers.toFn",function(a,b){"function"==typeof b&&(b=p(b));var c=a(b);return c["@@transducer/step"].bind(c)});g("transducers.first",V);g("transducers.ensureReduced",u);g("transducers.unreduced",w);g("transducers.deref",v);})();